task02, 03, 04
elpato42/javase02 pull request #1
Opened 2018-03-09 11:20 UTC by elpato42

2018-03-10 18:54 UTC, AnnaS91 requested changes

2018-03-10 18:54 UTC, AnnaS91 commented on src/main/App.java
> +        RecruitmentKit rk = new RecruitmentKit();
не ленитесь писать полные названия

2018-03-10 18:54 UTC, AnnaS91 commented on src/main/App.java
> +        for (Stationery s : stationeries
уехали отступы файла. Можно использовать ctrl+alt+L для форматирования

2018-03-10 18:54 UTC, AnnaS91 commented on src/main/t02t03t04/Employee.java
> +            this.stationeries.add(s);
а почуму не используете метод addAll()?

2018-03-10 18:54 UTC, AnnaS91 commented on src/main/t02t03t04/Employee.java
> +        } else {
как вариант, здесь можно было бы выбросить собственный exception

2018-03-10 18:54 UTC, AnnaS91 commented on src/main/t02t03t04/Employee.java
> +            price = price + st.getPrice();
можно использовать +=

2018-03-10 18:54 UTC, AnnaS91 commented on src/main/t02t03t04/Price.java
> +        this.reformat();
а где проверка на null и на соответствие ссылок?

2018-03-10 18:54 UTC, AnnaS91 commented on src/main/t02t03t04/comparator/SortedByNameAndPrice.java
> +            return sortByName.compare(o1, o2);
Вы дважды проводите сравнение. Лучше сохранить sortByName.compare(o1, o2) в переменную

2018-03-10 18:54 UTC, AnnaS91 commented on src/main/t02t03t04/comparator/SortedByPrice.java
> +        if(price1 < price2) {
обычно всё наоборот, если первый больше, то возвращается положительное число

2018-03-10 18:54 UTC, AnnaS91 commented on src/main/t02t03t04/stationery/CleaningTool.java
> +    public CleaningTool(String name, Price price) {
конструктор принято располагать сразу после объявления полей

2018-03-10 18:54 UTC, AnnaS91 commented on src/main/t02t03t04/stationery/ScaleTool.java
> +            return "none";
можно завести константу для "none"

2018-03-10 18:54 UTC, AnnaS91 commented on src/main/t02t03t04/stationery/ScaleTool.java
> +    public ScaleTool(String name, int length, String material, Price price) {
конструктор после объявления полей

2018-03-10 18:54 UTC, AnnaS91 commented on src/main/t02t03t04/stationery/CleaningTool.java
> +        switch (name.toLowerCase()) {
Чтобы избежать switch и иметь способность спокойно расширять enum, лучше использовать valueOf, перехватывая exception (это касается и свитчей в Ваших других классах)

2018-03-10 18:54 UTC, AnnaS91 commented on src/main/t02t03t04/stationery/Stationery.java
> +        if (object instanceof Stationery) {
где проверка на null и ссылки?

2018-03-10 18:54 UTC, AnnaS91 commented on src/test/t02t03t04/EmployeeTest.java
> +    Employee employee;
в тестах тоже стоит использовать модификаторы доступа

2018-03-10 18:54 UTC, AnnaS91 commented on src/test/t02t03t04/comparator/SortedByNameTest.java
> +        assertTrue(sortedByName.compare(pen, pen2) == 0);
можно использовать assertEquals

2018-03-10 21:35 UTC, elpato42 commented on src/main/t02t03t04/Employee.java
> +            this.stationeries.add(s);
век живи, век учись

2018-03-10 21:38 UTC, elpato42 commented on src/main/t02t03t04/comparator/SortedByPrice.java
> +        if(price1 < price2) {
Я хотела чтобы выводилось в порядке убывания. Наверное, лучше это сделать как-то как ниже, чтобы для потустороннего разработчика было понятно? (ну или переименовать компаратор немножко):
public int compare(Stationery o1, Stationery o2) {
        float price1 = o2.getPrice();
        float price2 = o1.getPrice();...}

2018-03-11 21:15 UTC, elpato42 commented on src/main/t02t03t04/comparator/SortedByNameAndPrice.java
> +            return sortByName.compare(o1, o2);
Я пропустила это замечание, когда правила код. Ссылку вам уже отправила, поэтому закидывать на почту не буду новыми, но у себя исправлю

2018-03-14 18:44 UTC, AnnaS91 approved these changes
Задания засчитываю, но порядок следования и модификаторы поправьте.

2018-03-14 18:44 UTC, AnnaS91 commented on src/main/t02t03t04/stationery/ScaleTool.java
> +    private Name name;
порядок следования: поля, конструктор, методы. Поэтому нужно перенести name наверх

2018-03-14 18:44 UTC, AnnaS91 commented on src/main/t02t03t04/stationery/ScaleTool.java
>      Material material;
а почему поля без модификаторов?

2018-03-23 16:07 UTC, merged