task 05
elpato42/javase02 pull request #2
Opened 2018-03-09 17:05 UTC by elpato42

2018-03-09 19:22 UTC, elpato42 commented on src/main/t05/model/Group.java
> +    public static class Assessment<A> {
Change Assessment to Mark

2018-03-10 21:10 UTC, AnnaS91 requested changes
Отличная работа! Хотелось бы увидеть больше тестов.

2018-03-10 21:10 UTC, AnnaS91 commented on src/main/t05/Run.java
> +        Student X = AllStudents.students.get(0);
переменные именуются с маленькой буквы, и лучше не использовать однобуквенные имена

2018-03-10 21:10 UTC, AnnaS91 commented on src/main/t05/Run.java
> +        Student Y = AllStudents.students.get(1);
аналогичное замечание

2018-03-10 21:10 UTC, AnnaS91 commented on src/main/t05/Run.java
> +                System.out.println(g.getDiscipline() + " " + g.getAssessment(X));
почему для х?

2018-03-10 21:10 UTC, AnnaS91 commented on src/main/t05/Run.java
> +        for (Group g: AllGroups.GROUP_SET
не ленитесь писать полное имя

2018-03-10 21:10 UTC, AnnaS91 commented on src/main/t05/model/Group.java
> +public String getDiscipline(){
отступы уехали

2018-03-10 21:10 UTC, AnnaS91 commented on src/main/t05/model/Group.java
> +    public static class Assessment<A> {
если мы предполагаем, что оценка это не вообще объект, а Double, Integer или Float, стоит отразить это в типе параметризации (т.е. использовать в заголовке класса не просто A, а, например, A extends Number)

2018-03-10 21:10 UTC, AnnaS91 commented on src/main/t05/model/Group.java
> +        private Assessment(A assessment){
почему private? уехали отступы

2018-03-10 21:10 UTC, AnnaS91 commented on src/main/t05/model/Group.java
> +        private A getAssessment() {
аналогичный вопрос

2018-03-10 21:10 UTC, AnnaS91 commented on src/main/t05/model/Student.java
> +        if(object instanceof Student){
проверка на ссылку и на null

2018-03-10 21:10 UTC, AnnaS91 commented on src/main/t05/model/Student.java
> +        return name.hashCode() * surname.hashCode() * course;
опасно, вдруг кто-то поставит course как 0?

2018-03-10 21:10 UTC, AnnaS91 commented on src/main/t05/model/Student.java
> +        course = 1;
ощущение, что курс поменять ни откуда нельзя

2018-03-10 21:24 UTC, elpato42 commented on src/main/t05/Run.java
> +        Student X = AllStudents.students.get(0);
Хорошо, про переменные и полные названия, надеюсь, окончательно поняла. Конкретно здесь, просто следовала на 100% формулировке задания про студента Х. Исправлю.

2018-03-10 21:24 UTC, elpato42 commented on src/main/t05/Run.java
> +                System.out.println(g.getDiscipline() + " " + g.getAssessment(X));
копировать-вставить. Плохо порефакторила

2018-03-10 21:31 UTC, elpato42 commented on src/main/t05/model/Student.java
> +        course = 1;
Ощущение верное. По скольку в  ТЗ *зачеркнуто* в домашнем задании нет подобных условий, я решила не усложнять себе жизнь, но добавить поле скорее для себя, если мне нечем будет заняться позднее

2018-03-11 20:54 UTC, merged

2018-03-11 20:59 UTC, elpato42 commented on src/main/t05/model/Group.java
> +        private Assessment(A assessment){
Посчитала, что мне не нужно обращаться больше ни от куда к этому классу, кроме как из Group. Разве что из теста