05 task
elpato42/javase02 pull request #4
Opened 2018-03-11 21:11 UTC by elpato42

2018-03-14 19:11 UTC, AnnaS91 requested changes
Тут все замечания вообще больше к третьему заданию относятся. Поэтому задание №5 засчитываю, а вот по третьему жду исправлений (давайте в этом же пул реквесте)

2018-03-14 19:11 UTC, AnnaS91 commented on src/main/t02t03t04/exception/NoSuchNameException.java
> +    public NoSuchNameException(String material) {
можно было бы это сообщение передавать в super конструктор

2018-03-14 19:11 UTC, AnnaS91 commented on src/main/t02t03t04/stationery/CleaningTool.java
> +    public CleaningTool(String name, Price price) {
конструктор должен располагаться сразу после объявления полей

2018-03-14 19:11 UTC, AnnaS91 commented on src/main/t02t03t04/stationery/CleaningTool.java
> +                //TODO throw NoSuchNameException();
кажется TODO можно уже раскомментировать

2018-03-14 19:11 UTC, AnnaS91 commented on src/main/t02t03t04/stationery/RecruitmentKit.java
> +     {
если static, то как мы с Вами и говорили, инициализацию тоже лучше сделать статиком

2018-03-14 19:11 UTC, AnnaS91 commented on src/main/t02t03t04/stationery/RecruitmentKit.java
> +            stationeries.add(new ScaleTool("ruler", 13, "plastic", new Price(20)));
несколько излишне, ведь тут Вы точно можете проверить, какими значениями инициализируете

2018-03-14 19:11 UTC, AnnaS91 commented on src/main/t02t03t04/stationery/ScaleTool.java
> +    int length;
почему без модификаторов?

2018-03-14 19:11 UTC, AnnaS91 commented on src/main/t02t03t04/stationery/ScaleTool.java
> +                    System.out.println(name + "can`t be shorter than 50");
а точно name, a не length? ;)

2018-03-14 19:11 UTC, AnnaS91 commented on src/main/t02t03t04/stationery/ScaleTool.java
> +                //TODO throw NoSuchNameException();
Вы же уже добавили exception, можете смело его использовать

2018-03-14 19:11 UTC, AnnaS91 commented on src/main/t02t03t04/stationery/ScaleTool.java
> +            this.name = Name.valueOf(name.toUpperCase());
как-то странно, получается, что name снова перезаписывается?

2018-03-14 19:11 UTC, AnnaS91 commented on src/main/t02t03t04/stationery/ScaleTool.java
> +    private Name name;
поля перед конструктором

2018-03-14 19:11 UTC, AnnaS91 commented on src/main/t02t03t04/stationery/Stationery.java
> +        return "none";
напрашивается константа для "none" в общем классе

2018-03-14 19:11 UTC, AnnaS91 commented on src/main/t02t03t04/stationery/WritingTool.java
> +            return "none";
см. выше

2018-03-16 12:46 UTC, elpato42 commented on src/main/t02t03t04/stationery/ScaleTool.java
> +                    System.out.println(name + "can`t be shorter than 50");
Точно, я мол говорю пользователю "Рулетка не может быть короче 50см" Вы когда нибудь видели 10сантиметровые рулетки?)) На самом деле это просто ради разнообразия, тут так же можно и исключение бросить, если очень надо.

2018-03-16 12:56 UTC, elpato42 commented on src/main/t02t03t04/Employee.java
> +        if (!stationeries.remove(stationery)) {
вот тут еще посмотрела на метод, упростила до невозможности
Убрала метод hasStationary, потому что только тут использовала, хотя теперь жалею, полезный метод, но если что можно вернуть

2018-03-17 13:20 UTC, AnnaS91 approved these changes
Третье задание зачтено

2018-03-17 13:20 UTC, AnnaS91 commented on src/main/t02t03t04/App.java
> +                ) {
всё-таки постарайтесь настроить идею так, чтобы ){ попадало на предыдущую строку

2018-03-17 13:20 UTC, AnnaS91 commented on src/main/t02t03t04/Employee.java
> +        if (!stationeries.remove(stationery)) {
в целом через has тоже хорошо было

2018-03-17 13:20 UTC, AnnaS91 commented on src/main/t02t03t04/Employee.java
> +            price += st.getPrice();
теперь точно знаете как это переписать через stream :)

2018-03-17 13:20 UTC, AnnaS91 commented on src/main/t02t03t04/stationery/Stationery.java
> +            if (!this.manufacturerCompany.equals(newObject.getManufacturerCompany())) {
ещё проверить случай с this.manufacturerCompany == null, а то в данном случае рискуете сорвать NPE

2018-03-23 16:07 UTC, merged